//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Felhasznalok
    {
        public int Id { get; set; }
        public string Felhasznalo { get; set; }
        public string jelszo { get; set; }
    }
}
