//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penztarcak
    {
        public int Id { get; set; }
        public string nev { get; set; }
        public string marka { get; set; }
        public string nem { get; set; }
        public string szin { get; set; }
        public string masodlagoskod { get; set; }
    }
}
