//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tárhelyek
    {
        public int Id { get; set; }
        public int cikkszamFK { get; set; }
        public int tarhelykod { get; set; }
    
        public virtual Cikkszámok Cikkszámok { get; set; }
    }
}
